version: '3.5'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    ports:
        - "8081:8081"
        - "8080:8080"
  frontend:
    build: 
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"